[package]
name = "journaldeliver"
version = "0.1.0"
authors = ["Andre Stemmet <andre.stemmet@jci.com>"]
edition = "2018"

[dependencies]
config = "0.9.0"
serde_yaml = "0.8.4"
serde_json = "1.0.27"
clap = "2.32.0"
journald = "0.4.0"
syslog = "4.0.1"
lazy_static = "1.1.0"
notify = "4.0.6"
