[package]
name = "journaldeliver"
version = "0.1.3"
authors = ["Andre Stemmet <andre.stemmet@jci.com>"]
edition = "2018"

[dependencies]
config = "0.9.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_yaml = "0.8.6"
serde_json = "1.0.32"
clap = "2.32.0"
systemd = "0.3.0"
syslog = "4.0.1"
notify = "4.0.6"
parse_duration = "1.0.1"
chrono = "0.4.6"
failure = "0.1.2"
lazy_static = "1.1.0"


