#license_template_path = ""
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
disable_all_formatting = false
edition = "2018"
emit_mode = "Files"
empty_item_single_line = false
error_on_line_overflow = false
error_on_unformatted = false
fn_args_density = "Vertical"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
hide_parse_errors = false
ignore = []
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
make_backup = true
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true 
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Never"
report_todo = "Never"
required_version = "0.99.5"
skip_children = false
space_after_colon = true
space_before_colon = true
spaces_around_ranges = true
struct_field_align_threshold = 30
struct_lit_single_line = false
tab_spaces = 3
trailing_comma = "Always"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = false
wrap_comments = true
