
filebeat.inputs:
- type: tcp
  max_message_size: 8MiB
  host: "localhost:9000"
  enabled: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
fields:
  env: paddi
setup.kibana:
  host: "localhost:5601"
processors:
  - decode_json_fields:
      fields: 
        - "message"
      target: ""
      overwrite_keys: true
output.elasticsearch:
  hosts: 
    - "localhost:9200"
    